### ISSUE TITLE
ActiveResource::Collection Responding to .empty?

### ISSUE THREAD

**Issue by tomrossi7** [rails/activeresource#104]
I am not sure if this is an oversight or something I am doing wrong, but when upgrading my ActiveResource with Rails 4 I've had to modify all references to .empty? from ActiveResource::Collection objects.  I noticed that it does respond to .any?  It would seem like we would want that method defined so the collection more closely resembles array collections.

**Comment by rafaelfranca** [comment]
I'll cut a release soon. Closing since it is already fixed. Let me know if it is not working.
