### ISSUE TITLE
Create/Update doesn't actually put parameters into named attribute

### ISSUE THREAD

**Issue by dbackeus** [rails/activeresource#151]
From the README regarding creating records:
```ruby
# {"person":{"first":"Tyler","last":"Durden"}}
#
# is submitted as the body on
#
# POST http://api.people.com:3000/people.json
#
# when save is called on a new Person object.  An empty response is
# is expected with a 'Location' header value:
#
# Response (201): Location: http://api.people.com:3000/people/2
#
tyler = Person.new(:first => 'Tyler')
tyler.new?  # => true
tyler.save  # => true
tyler.new?  # => false
tyler.id    # => 2
```

According to this the parameters should be wrapped in a `person` top attribute like:
`{"person":{"first":"Tyler","last":"Durden"}}`

In reality it just sends the parameters as a flat hash like:
`{"first":"Tyler","last":"Durden"}`

What's up?

**Comment by dbackeus** [comment]
After diving into the activeresource code we realised this is because of the `include_root_in_json` setting. Would be nice if the README could be updated to reflect this. Especially as the default value is `false`.

**Comment by ramontayag** [comment]
@dbackeus please submit a pull request to update the readme.
