### ISSUE TITLE
`where` do not works for an `ActiveResource::Collection`

### ISSUE THREAD

**Issue by om-nishu-trantor** [rails/activeresource#154]
Right now if we run `where` on an ActiveResource class it works, but when we run on an object of `ActiveResource::Collection` returned by the where operation on AR class it do not works.
On the contrary it works for an ActiveRecord::Collection.
There should be something similar to that in ActiveResource also.

```
collection = ActiveresourceModel.where(clause_one: 'one')
collection = collection.where(clause_two: 'two') # it should return results with combination of both the query parameters.
```

**Comment by om-nishu-trantor** [comment]
I've added a solution for this over here
https://github.com/rails/activeresource/pull/153

**Comment by om-nishu-trantor** [comment]
@rafaelfranca Could you share your thoughts on this feature/Issue ?

**Comment by amita-trantor** [comment]
Needed this one.. :+1: thanks @om-nishu-trantor 
Not sure it is still not merged, why ?

**Comment by andvikram** [comment]
Good to have.. :+1:
