### ISSUE TITLE
How to change request url structure

### ISSUE THREAD

**Issue by trkrameshkumar** [rails/activeresource#182]
Hi Guys,

Is there a configuration option avilable in  ActiveResource to change the request url structure

for example when my client application try to access  services of particular user from the api,   ActiveResource sending request to url in the following structure 

``/api/v1/services.json?user_id=1``

but instead i want the ActiveResource to send request like this 

``/api/v1/users/1/services``

These are the two model files for reference
```
#user.rb
 class User < ActiveResource::Base 
   self.site = "http://localhost:3001/api/v1"
   has_many :services
 end
```

```
 #service.rb
 class Service < ActiveResource::Base
  self.site = "http://localhost:3001/api/v1"
  belongs_to :user
end
```

Any help , would be greatly appreciated.

Thanks.

**Comment by trkrameshkumar** [comment]
http://stackoverflow.com/questions/32024934/how-to-change-request-url-structure-in-activeresource-ruby-gem

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
