### ISSUE TITLE
Errors when attempting to use with Rails 5.0.0-beta3

### ISSUE THREAD

**Issue by kylehayes** [rails/activeresource#215]
Not sure if activeresource is fully supported in Rails 5 beta 3 yet, but I attempted to point my Gemfile declaration at the master branch and received the following errors when doing `bundle install`:

```
Bundler could not find compatible versions for gem "activemodel":
  In Gemfile:
    activeresource was resolved to 5.0.0, which depends on
      activemodel-serializers-xml (~> 1.0) was resolved to 1.0.0, which depends on
        activemodel (> 5.x)

    activeresource was resolved to 5.0.0, which depends on
      activemodel (~> 5.x)

    rails (< 5.1, >= 5.0.0.beta3) was resolved to 5.0.0.beta3, which depends on
      activemodel (= 5.0.0.beta3)

    rails (< 5.1, >= 5.0.0.beta3) was resolved to 5.0.0.beta3, which depends on
      activemodel (= 5.0.0.beta3)

    activeresource was resolved to 5.0.0, which depends on
      rails-observers (~> 0.1.2) was resolved to 0.1.2, which depends on
        activemodel (~> 4.0)
```

**Comment by bentremblay** [comment]
It's requesting a version of rails-observers (0.1.2) which doesn't support Rails 5. If you're still having this issue, I fixed it temporarily by adding the master branch of rails-observers to my Gemfile:

```
gem 'rails-observers', github: 'rails/rails-observers'
gem 'activeresource', github: 'rails/activeresource'
```

**Comment by MassMadankumar** [comment]
C:\Users\Madan\Desktop\ruby\my_shopify_app>rails generate shopify_app:install
The git source git://github.com/rails/rails-observers.git is not yet checked out
. Please run `bundle install` before trying to start your application

C:\Users\Madan\Desktop\ruby\my_shopify_app>rails generate shopify_app --api_key
e2d26c9b5bb3f0262b24510ec5cfb1a8 --secret e5ba3a2dd94abdfb54c0d00b53ba9776
The git source git://github.com/rails/rails-observers.git is not yet checked out
. Please run `bundle install` before trying to start your application
