### ISSUE TITLE
Token authorization broken in 4.1

### ISSUE THREAD

**Issue by bvogel** [rails/activeresource#219]
After upgrading from 4.0.0 to 4.1.0 our token authorization stopped to work.
We use a piece of code almost identical to the manual:

``` (ruby)
class Customer < ActiveResource::Base
  self.site = CONFIG[:site]
  self.prefix = '/api/v1/'
  headers['Authorization'] = "Token token=\"#{Authenticator.current_token}\""
end
```

with `Authenticator` being:

``` (ruby)
class Authenticator
  def self.current_token
    if CONFIG[:token].blank?
      params = {'user' => CONFIG[:user], 'password' =>CONFIG[:password]}.to_json
      url = CONFIG[:site] + '/authorization/api/v1/login'
      uri = URI.parse(url)
      result = ''
      if uri.scheme == 'https'
        Net::HTTP.start(uri.host, uri.port,
                        use_ssl: true,
                        verify_mode: OpenSSL::SSL::VERIFY_NONE) do |http|
          result = handle_request(http, uri, params)
        end
      else
        Net::HTTP.start(uri.host, uri.port) do |http|
          result = handle_request(http, uri, params)
        end
      end
      CONFIG[:token] = result['token']
    end
    CONFIG[:token]
  end

  class << self
    private

    def handle_request(http, uri, params)
      # http.open_timeout = @config.http_open_timeout
      # http.read_timeout = @config.http_read_timeout

      request = Net::HTTP::Post.new(uri.path, 'Content-Type' => 'application/json')
      request.body = params
      response = http.request request

      case response
        when Net::HTTPSuccess then
          JSON.parse(response.body)
        when Net::HTTPUnauthorized then
          raise 'Unauthorized'
        else
          raise
      end
    end
  end
end
```

After a server start the token will be acquired and sometimes the first call will even have a token. All subsequent calls are missing the token header. Going back to 4.0.0 will fix this issue immediately. Do you need any further data?

**Comment by bvogel** [comment]
Something additional we just found: when using the Rails console all calls do have a token and everything works as expected.

**Comment by rafaelfranca** [comment]
How the token is being configured? If it is being configured inside a
thread only that thread will have that token value configured. Make sure it
is set before your servers create new threads.

**Comment by bvogel** [comment]
How would I manage that? It is configured as shown above on a Apache/Passenger combo, but even under two webrick servers (one being the AR-host, other being the AR-client) in the dev-Environment it fails. So I doubt that threading may be an issue.

**Comment by rafaelfranca** [comment]
The only change in Active Resource 4.1 is related to thread safety in the headers. Could you reproduce this issue in an example application so I can investigate it?

**Comment by rafaelfranca** [comment]
it would be also helpful if you could bisect the activeresource change that caused this behavior.

**Comment by bvogel** [comment]
I can't help with bisecting (haven't done that) but I created a simple project to reproduce the issue: https://github.com/bvogel/activeresource_issue219. It contains two parts, a server and a client. When running both applications as servers `~/client $ rails s` and `~/server $ rails s` opening `http://localhost:3001/test_objects` will show a list of TestObjects, but opening each TestObject through the `Show`-link I get a 401 error. When using `~/client $ rails c` calling `TestObject.all` or `TestObject.find(1)` will work just fine. After some time It may work even through the server, but clearing the `tmp` folder will recreate the failure. Please advice any further information required.

**Comment by bvogel** [comment]
So I did the bisect and turns out that the "threadsafe header" commit (https://github.com/rails/activeresource/commit/6101794a6571e2ac5078ff65490e962563980591) is to blame. Question is, is this a desired behavior and we have to account for this or is it an legitimate issue?

**Comment by bvogel** [comment]
Hi, any more information is needed, please advice!

**Comment by rafaelfranca** [comment]
Sorry but right now I don't have time to look at this issue. If it is important to you please do investigate a possible fix.

**Comment by bvogel** [comment]
Currently we "worked around" by version locking to which doesn't seem to be the right thing to do in the long run 😢

**Comment by bvogel** [comment]
@rafaelfranca Any chance you'll find time to look into this issue now?

**Comment by frozenfung** [comment]
Got the same problem here. Downgrade to 4.0.0 already.

**Comment by repinel** [comment]
The `headers` attribute is not being shared between threads because it is always [initialized with an empty hash](https://github.com/rails/activeresource/blob/f4bec7f8f389a203c51bdeaac02addc0bca7ce43/lib/active_resource/base.rb#L655), and `ThreadsafeAttributes` only [checks if the attribute has been defined](https://github.com/rails/activeresource/blob/f4bec7f8f389a203c51bdeaac02addc0bca7ce43/lib/active_resource/threadsafe_attributes.rb#L60), not if it is present.

```ruby
  def test_header_should_be_copied_to_main_thread_if_not_defined
    fruit = Class.new(ActiveResource::Base)

    Thread.new do
      fruit.site = 'http://market'
      assert_equal 'http://market', fruit.site.to_s

      fruit.headers['key'] = 'value'
      assert_equal 'value', fruit.headers['key']
    end.join

    assert_equal 'http://market', fruit.site.to_s
    assert_equal 'value', fruit.headers['key']
  end
```

In that test case, the `site` attribute will be copied from the new thread to the main one, but not `headers`.

@rafaelfranca thoughts?

**Comment by rafaelfranca** [comment]
but would not the headers attribute being set only if you read it?

**Comment by repinel** [comment]
Yes. When calling `fruit.headers` inside the new thread (current), the main thread will also get the [default empty hash](https://github.com/rails/activeresource/blob/f4bec7f8f389a203c51bdeaac02addc0bca7ce43/lib/active_resource/base.rb#L655). However, a new hash will be created when [applying the `superclass.headers`](https://github.com/rails/activeresource/blob/f4bec7f8f389a203c51bdeaac02addc0bca7ce43/lib/active_resource/base.rb#L657), and that will be one holding the header `key`.
So since it's a new instance of a hash, no changes will be applied to the main thread.

**Comment by bvogel** [comment]
Thank you for looking into this! 

As I understand the current release situation from #228 there will be no release soon(-ish). Could you please apply the fix unto the 4-stable branch so I can use it?

**Comment by rafaelfranca** [comment]
It is applied already. I'll try to work in a release this week.
