### ISSUE TITLE
Bug: Base.find(:first) no longer loads lazily.

### ISSUE THREAD

**Issue by apepper** [rails/activeresource#220]
Since https://github.com/rails/activeresource/pull/88/files#diff-36351a602aa8104f544d1fe1f9fa34d2R874 `find(:first)` is no longer lazy. Instead it fetches _all_ items from the server and than returns the first one. If there are a lot of items to be fetched, this can be really slow for "just" the first item.

I would expect, that `find(:first)` only requests as little items as possible from the server.

**Comment by rafaelfranca** [comment]
Was it ever lazy? Looking in the code it always requested all items and got the first one.

**Comment by apepper** [comment]
### To reproduce

* Use [`infopark_crm_connector`](https://rubygems.org/gems/infopark_crm_connector), which uses `activeresource` internally.
* Set logging to `STDOUT`:
    ```ruby
    logger = Logger.new(STDOUT)
    logger.level = Logger::INFO
    ActiveResource::Base.logger = logger
    ```
* Run a `first` query, e.g. `Infopark::Crm::Contact.first; 'done'`.

### Expected

```
irb(main):001:0> Infopark::Crm::Contact.first; 'done'
I, [2017-05-05T10:43:21.876152 #6846]  INFO -- : GET https://example.com:443/api/contacts.json
I, [2017-05-05T10:43:21.876465 #6846]  INFO -- : --> 200 OK 10817 (289.0ms)
=> "done"
```

### Actual

```
irb(main):001:0> Infopark::Crm::Contact.first; 'done'
I, [2017-05-05T10:43:46.483185 #6937]  INFO -- : GET https://example.com:443/api/contacts.json
I, [2017-05-05T10:43:46.483493 #6937]  INFO -- : --> 200 OK 10817 (256.2ms)
I, [2017-05-05T10:43:46.780512 #6937]  INFO -- : GET https://example.com:443/api/contacts.json?continuation_handle=eyJtb2RlbF9uYW1lIjoiQ29udGFjdCIsImZyb20iOjEwfQ
I, [2017-05-05T10:43:46.780593 #6937]  INFO -- : --> 200 OK 10028 (285.3ms)
I, [2017-05-05T10:43:47.052705 #6937]  INFO -- : GET https://example.com:443/api/contacts.json?continuation_handle=eyJtb2RlbF9uYW1lIjoiQ29udGFjdCIsImZyb20iOjIwLCJsaW1pdCI6MTB9
I, [2017-05-05T10:43:47.052866 #6937]  INFO -- : --> 200 OK 10066 (269.4ms)
I, [2017-05-05T10:43:47.326119 #6937]  INFO -- : GET https://example.com:443/api/contacts.json?continuation_handle=eyJtb2RlbF9uYW1lIjoiQ29udGFjdCIsImZyb20iOjMwLCJsaW1pdCI6MTB9
I, [2017-05-05T10:43:47.326227 #6937]  INFO -- : --> 200 OK 10273 (269.0ms)
I, [2017-05-05T10:43:47.613564 #6937]  INFO -- : GET https://example.com:443/api/contacts.json?continuation_handle=eyJtb2RlbF9uYW1lIjoiQ29udGFjdCIsImZyb20iOjQwLCJsaW1pdCI6MTB9
I, [2017-05-05T10:43:47.613672 #6937]  INFO -- : --> 200 OK 10317 (283.3ms)
I, [2017-05-05T10:43:47.907452 #6937]  INFO -- : GET https://example.com:443/api/contacts.json?continuation_handle=eyJtb2RlbF9uYW1lIjoiQ29udGFjdCIsImZyb20iOjUwLCJsaW1pdCI6MTB9
I, [2017-05-05T10:43:47.907559 #6937]  INFO -- : --> 200 OK 10352 (289.5ms)
[...]
```

### Affected versions

I tried different versions of `activeresource`:

* `4.0.0` - working as expected
* `4.1.0` - __not__ working as expected
* `5.0.0` - __not__ working as expected

I also did a `git bisect` between `4.0.0` and `4.1.0` of `activeresource`, which pointed at 6438124875a8caaa19fb182cde3c7402cd56dc84 being the fist "bad" commit: 

```
6438124875a8caaa19fb182cde3c7402cd56dc84 is the first bad commit
commit 6438124875a8caaa19fb182cde3c7402cd56dc84
Author: Rafael França <rafaelmfranca@gmail.com>
Date:   Mon Nov 30 17:20:01 2015 -0200

    Merge pull request #88 from rfletcher/master

    Exception on 404 with .find(:first), .find(:last)

:040000 040000 38fe61482e06ccd52b92bc6dbb0a0755bbdfac52 1aadcfcc6dabeba26653fa009aea724af82a633c M	lib
:040000 040000 b0be0a62b45f80b0ebf01ff79fa2a4fe78fd013d 9f420fb11cfdf996546387e3c28f7573289dc987 M	test
```

**Comment by rafaelfranca** [comment]
I tried to reproduce in the test suite and could not. Every time I call `first` only one request is done to `GET http://37s.sunrise.i:3000/people.json`. Could you try to reproduce it in our test suite?

**Comment by rafaelfranca** [comment]
Just to be clear. I could not find anything in the codebase that says that calling `to_a` in a `ActiveResource::Collection` do more requests. It just returns `elements` and `elements` are passed to the initializer already https://github.com/rails/activeresource/blob/master/lib/active_resource/collection.rb#L61.

So I'm trying to reproduce this so I can see. I can't use a gem because maybe it is the gem that is causing this behavior so we need to reproduce it in Active Resource in isolation.

**Comment by rafaelfranca** [comment]
What is even more strange that `ActiveResource::Collection#first` just delegate to `to_a`. I'm having a really hard time to understand how calling `to_a` could change any behavior and tried to replicate the behavior you described a lot without success.

**Comment by rafaelfranca** [comment]
Ah, seems you project is monkey patching Active Resource https://github.com/infopark/crm_connector/blob/master/lib/crm_connector/core/continuation_support.rb#L13 and this is why you are seeing different behavior.

**Comment by rafaelfranca** [comment]
I fixed your issue even that it is not an Active Resource issue, but next time it would be great if you provide the information that you are relying in a behavior of a monkey patch.

**Comment by apepper** [comment]
> I fixed your issue even that it is not an Active Resource issue, but next time it would be great if you provide the information that you are relying in a behavior of a monkey patch.

Thank you very much. I did not even think of the monkey patch during reporting. Next time I'll have a loser look at our monkey patches before reporting and if I report I'll include all monkey patches.
