### ISSUE TITLE
v5.0.0 not on Rubygems?

### ISSUE THREAD

**Issue by jemminger** [rails/activeresource#228]
It looks like v5 was committed Sept 2015:  https://github.com/rails/activeresource/commit/ef49f510b73d273326d3c52825529177fe03f569

Is it not ready for production use?

**Comment by rafaelfranca** [comment]
It is not ready yet, and maybe will never be. I recommend using the git version. It took 3 years to the version 4.1.0 be released and it may happen the same with 5.0.0.

For now I know there are some bugs that needs to be fixed before the release happening.

**Comment by brenes** [comment]
Do you have any roadmap or bug list? Maybe the community could continue with the work in ActiveResource if it's going to be discontinued.
