### ISSUE TITLE
release for rails 5 support

### ISSUE THREAD

**Issue by Aethelflaed** [rails/activeresource#230]
Hello,

I have activeresource as a dependency of a private gem, and I currently can't upgrade to rails 5 because (among other) of activeresource and it's dependency to activemodel 4.

Is this release already scheduled ?
I can't simply specify the github repository in my gemspec, it doesn't work that why, sadly.

If there is any work left to be done before being able to release it, point me to the right location, I may spend some time helping then

**Comment by rafaelfranca** [comment]
Dup of https://github.com/rails/activeresource/issues/228
