### ISSUE TITLE
Released version does not work with Rails 5

### ISSUE THREAD

**Issue by ralfebert** [rails/activeresource#232]
When added in a Rails 5 app, dependencies cannot be resolved:

```
Bundler could not find compatible versions for gem "activesupport":
  In snapshot (Gemfile.lock):
    activesupport (= 5.0.0.1)

  In Gemfile:
    activeresource was resolved to 2.0.1, which depends on
      activesupport (= 2.0.1)

    rails (>= 5.0.0.1, ~> 5.0.0) was resolved to 5.0.0.1, which depends on
      activejob (= 5.0.0.1) was resolved to 5.0.0.1, which depends on
        globalid (>= 0.3.6) was resolved to 0.3.7, which depends on
          activesupport (>= 4.1.0)
```

Getting it from the live master branch works:

```
gem 'activeresource', github: 'rails/activeresource', branch: 'master'
```

It would be great if there would be a released gem for Rails 5 / if the README would mention to use the master branch for the moment.

**Comment by rafaelfranca** [comment]
Don't expect releases of active resources. The last release took 3 years to be made. Use the master branch and when it is ready the gem will be released

**Comment by ralfebert** [comment]
Wouldn't it make sense to mention it in the readme then?
Otherwise the first impression of the 'activeresource' gem will be 'it's broken'.
https://github.com/rails/activeresource/pull/233
