### ISSUE TITLE
Lack of 5.0 gem prevents other gems from depending on activeresource

### ISSUE THREAD

**Issue by davidw** [rails/activeresource#234]
It's possible to directly depend on 5.0 compatible code like so:

`gem 'activeresource', github: 'rails/activeresource', branch: 'master'`

But that's only for direct dependencies.  If another gem wants to depend on some kind 5.0 version of this one then it's a problem.

**Comment by brenes** [comment]
If it's a dependency those gems could require version 5.0. You would have to put the git line on your gemfile so bundle can solve itwhen looking for the dependencies. 

E.g: Imagine you have a gem called awesome_resources. Your gemspec should require 5.0 version as needed:

```
 add_dependency('activeresource', '> 5')
```

And your Gemfile should include both dependencies:

```
gem 'awesome_resource'
gem 'activeresource', github: 'rails/activeresource', branch: 'master'
```

This way bundle will look the active resource gem in github and the dependency would be accomplished.

Still, it's quite sad not having any release plan for ActiveResource as I read in #228 :cry:

**Comment by rafaelfranca** [comment]
Yeah, for now point to the master branch

**Comment by hovissimo** [comment]
I don't understand why using the master branch directly is the correct approach instead of releasing a gem.  If master works, why can't it be released?
