### ISSUE TITLE
Authorization header use case

### ISSUE THREAD

**Issue by mehmetdavut** [rails/activeresource#235]
Hi,

I am using activeresource in my Client Application. A Rails API creates token by username, password. And i set it to session[:access_token] in Client Application, and add this session[:access_token] to ActiveResource::Base.headers['Authorization'] before every request.

But it does not use actual access_token in session store, it uses previous one. I searched on internet but didn't find a solution to pass token from my dynamic controller to active resource header. What is the use case of the headers section, in ActiveResource documentation:

```
class Person < ActiveResource::Base
  self.headers['Authorization'] = 'Token token="abcd"'
end
```

I need this token value dynamic, from session variable.

**Comment by rafaelfranca** [comment]
There is no way to do that. The headers are at class level and once you change it, it will keep that value until you change it again.
