### ISSUE TITLE
ActiveResource with namespaced resources?

### ISSUE THREAD

**Issue by ttrmw** [rails/activeresource#241]
I have an application with routes like:

```
namespace :api do
  namespace :v1 do
    resources :things
  end
end
```

What's the right way to connect to `things` with ActiveResource? Right now it looks a whole lot like I will have to implement `custom_method_collection_url` but that doesn't feel too good.

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
