### ISSUE TITLE
Use where.not in active resource

### ISSUE THREAD

**Issue by anupamkakade** [rails/activeresource#246]
Hi, 

I wanted to use `where.not` similar to this [link](http://edgeguides.rubyonrails.org/active_record_querying.html#not-conditions)  with active  resource model. How can i achieve that ?

**Comment by rafaelfranca** [comment]
Hi. This method is not present in Active Resource and we don't have any plans to implement.

**Comment by rafaelfranca** [comment]
Sorry, hit the button too fast. It is hard to make a negation operator in an API call because the API server will not know what a not translate to.
