### ISSUE TITLE
ActiveResource find calls active record init

### ISSUE THREAD

**Issue by Cremz** [rails/activeresource#249]
I have a simple ActiveResource class. When i do .all it gets results from api. when i do find by an id it fails with error
```
ArgumentError: wrong number of arguments (given 2, expected 0..1)
```
which i discovered is triggered here:
activerecord-5.1.0/lib/active_record/core.rb:330
This only happens in production mode, in development it is fine. I don't have any other stacktrace, no clue how to debug. Why would an ActiveResource model trigger init for active record and only on production? it happens both on my dev machine when i start the server, in console as well as on the deployment server.  
i already opened a question on stack: http://stackoverflow.com/questions/43992844/active-resource-find-doesnt-work-in-production

**Comment by geetfun** [comment]
I'm experiencing the same issue. Similarly, it doesn't show up in development but only in production.

Not sure how to even test for this.

The backtrack doesn't show a call to ActiveRecord as @Cremz mentioned, however.

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by ooeyuna** [comment]
I have occur this issue too, it casue by class name conflict.

![9154ce1d-5468-4f15-b47f-7c4e34a7c80b](https://cloud.githubusercontent.com/assets/10668201/26627164/710ffbfc-4634-11e7-9872-d16cc7af4a7e.png)

normally, it should create new ActiveResource 'Container'. but it found 'Container' model, and use wrong class to initialize object.

**Comment by arturtr** [comment]
I found that `self.include_root_in_json = true` is reason by this error in my case

If switched it off, I cann't to create resource because it require root element.

Can we use root only for create?

**Comment by arturtr** [comment]
Switch format to  ActiveResource::Formats::XmlFormat solve the issue in my case

**Comment by arturtr** [comment]
But in this case I missed collection attributes like total_count

I tried to write activeresource wrapper for http://www.redmine.org/projects/redmine/wiki/Rest_Issues

**Comment by arturtr** [comment]
Version from master branch fixes issue with JSON with root

**Comment by arturtr** [comment]
@geetfun advice helps me to solve tis problem

> The problem is encountered when the AR source returns data that has more than 1 level deep of nested data. For whatever reason, AR::Base#find_or_create_resource_for is unable to instantiate it properly.
>
> The workaround is to pre-define these nested resources in a separate file 

I solve it in this manner

```ruby
class Redmine::API::CRM::Issue < Redmine::API::CRM::Base
  class IssueCollection < ActiveResource::Collection
    attr_reader :limit, :offset, :total_count

    def initialize(parsed = {})
      @elements = parsed['issues']
      @total_count = parsed['total_count']
      @offset = parsed['offset']
      @limit = parsed['limit']
    end

    def total_pages
      total_count / limit + 1
    end

    def current_page
      offset / limit + 1
    end
  end

  self.collection_parser = IssueCollection

  class Project < Redmine::API::Base; end
  class Tracker < Redmine::API::Base; end
  class Status < Redmine::API::Base; end
  class Priority < Redmine::API::Base; end
  class Author < Redmine::API::Base; end
  class AssignedTo < Redmine::API::Base; end
end

class Redmine::API::Base < ActiveResource::Base
  self.site = APP_CONFIG['redmine_url']

  def self.api_key
    Rails.application.secrets.redmine_api_key
  end

  self.headers['X-Redmine-API-Key'] = api_key
end
```

Also I removed `self.include_root_in_json = true` from Base class and place it in resources for POST requests.

**Comment by alistairholt** [comment]
I'm still experiencing this issue.

**Comment by Cremz** [comment]
It happens when the resource you are trying to access has a more complex structure (objects as values).
But it doesn't happen all the time, I have an application running perfectly normal when loading resources with objects 3-4 levels deep. But i recently created a new app that uses the same api and I do get that error.

**Comment by Cremz** [comment]
I bumped into this issue again this evening. Here's what happens
if you have a model called Writer which has_many :books and also the model Book defined in your activeresource application, if your Writer json returns an array of books, those books can only have keys and values (strings, integers, boolean)
for example:
writer.json: 
`{ 
  id: 1,
  books: [
    { id: 1, name: "book", details: { some_key: "some_value" } }
  ]
}`
this will break. active resources sees that Book is defined as an association, and when it tries to parse the details (Hash) it will break.

**Comment by cschmeichel** [comment]
@ivanbrennan I'm experiencing the same issue. Did you find a workaround?

**Comment by ivanbrennan** [comment]
@cschmeichel Unfortunately, no. I ended up removing ActiveResource from the project and handling the network calls directly, using RestClient.

**Comment by FilisLiu** [comment]
In my case, placing ActiveResource models in the same directory (app/models) as ActiveRecord was the reason. 

I solved it by defining the model within a module to create a distinct namespace such as `Api::Model.find`
