### ISSUE TITLE
Site property is cut during tests

### ISSUE THREAD

**Issue by firstsano** [rails/activeresource#251]
Got Model:
```
class User < ActiveResource::Base
  self.site = "http://awesome.com/api/v2r"
end
```
Got mocking in spec file:
```
ActiveResource::HttpMock.respond_to do |mock|
    mock.post "/users/login", json_headers, output.to_json
end
```
And got errors:
```
Could not find a response recorded for <POST: /api/v2r/users/login.json [{"Content-Type"=>"application/json"}] ()> - Responses recorded are: ["<POST: /users/login [{\"Accept\"=>\"application/json\"}] ()>"]
```
Question is - why it partially ignores `site` property during  the test?

**Comment by rafaelfranca** [comment]
Was the site ignored? It seems to be there: `/api/v2r/users/login.json`. There are two things incorrect in your mock. The URI is not correct, you need to pass the entire path (leaving the post out of the path). The headers are also not matching. You recorded `{"Accept"=>"application/json"}` but the request is with `{"Content-Type"=>"application/json"}`.

**Comment by firstsano** [comment]
Thanks for the reply.
I've fixed mismatched headers and used `/api/v2r/users/login.json` in the mock and everything works... BUT, I feel a little uncomfortable that I have to include part like `/api/v2r` which is the part of `site` property. I thought that if I set the `site` property then in a mock I need to specify uri's which should be relative to that property?

**Comment by firstsano** [comment]
Ok, got it working, my apologies
