### ISSUE TITLE
Using associations with custom path

### ISSUE THREAD

**Issue by tbhockey** [rails/activeresource#257]
Our API routes on the server-side are namespaced under `/api/v1/` (for example `/api/v1/posts_controller.rb`). This works fine on the primary model we are using ActiveResource with, Brands, see below.

```
class Brand < ActiveResource::Base
  self.site = Rails.configuration.bluebook_base_url + "/api/v1/"
  has_one :custom_page
end
```

```
class CustomPage < ActiveResource::Base
  self.site = Rails.configuration.bluebook_base_url + "/api/v1/"
  belongs_to :brand
end
```

However, when if I take a brand object and now fetch its associated `CustomPage` it is not looking under `/api/v1/`.

```
# Request
> b = Brand.find('foo')

# Server log
"GET /api/v1/brands/foo HTTP/1.1" 200

# Request
> b.custom_page

# Server log
"GET /brands/123/custom_page.json HTTP/1.1" 404
```

Is there any way to configure the path for an association?

**Comment by rafaelfranca** [comment]
Right now it is not possible. PRs are welcome.

**Comment by ingolfured** [comment]
I'm quite interest in this feature as well. Will make a PR soon if I get the chance to. Why is this closed again?

**Comment by moeffju** [comment]
I’m running into the same issue. Any pointers where to start looking into this?

**Comment by tbhockey** [comment]
Unfortunately i never had the time to come up with a solution. iirc I just built an endpoint to call the association directly, rather than through the parent. But yea, i really hope someone can make a PR for this. 

And yea, not really sure why it got closed either; this seems like a pretty necessary feature.

**Comment by moeffju** [comment]
Fairly sure the issue is [line 171 in associations.rb](https://github.com/rails/activeresource/blob/4c022c757579dd2e8189d87ef0dc9c97b47f67a0/lib/active_resource/associations.rb#L171): For `has_one`, the prefix options are never applied.

**Comment by moeffju** [comment]
https://github.com/moeffju/activeresource has a fix that works for my use case

**Comment by tbhockey** [comment]
That's beautiful, PR that! :)
