### ISSUE TITLE
Nested attributes: 'fields_for' missing 'child_index'

### ISSUE THREAD

**Issue by aljoshagasser** [rails/activeresource#269]
Hello everyone

I'm playing around with ActiveResource for some weeks now and was able to find a solution for almost all problems regarding nested attributes / associations in general. Anyway I now have a problem with the nested attributes for a "Feedback" form:

```
<%= form_for @feedback %>
  <% @questions.each_with_index do |question, index| %>
    <%= f.fields_for :feedback_answers, FeedbackAnswer.build, child_index: index do |builder| %>
      <%= render "feedback_answer_fields", f: builder, question: question %>
    <% end %>
  <% end %>
<% end %>
```
The form is generated properly with one thing missing: the child_index is not set, e.g. instead of
`<input type="hidden" name="feedback[feedback_answers][0][rating]" value="">`
the output looks like this
`<input type="hidden" name="feedback[feedback_answers][rating]" value="">`

As you can see I've tried to set the child_index manually cause I thought it could have something to do with how "build" works in ActiveResource. Didn't work neither.

I would really appreciate your help.

**Comment by aljoshagasser** [comment]
Okay I've found a solution for the fields_for inputs to be generated properly (including the child_index). Since `accepts_nested_attributes_for` isn't working with ActiveResource, I've added the following method to my Feedback model (which is normally created by `accepts_nested_attributes_for` - https://apidock.com/rails/v3.2.3/ActiveRecord/NestedAttributes/ClassMethods/accepts_nested_attributes_for):
```
def feedback_answers_attributes=(attributes)
end
```

Now I don't really know how to replicate that method in order to work properly with ActiveResource. All I know is, that my fields are generated properly. However, when I submit the Feedback form, I get the following error message (my params look alright): `NameError (wrong constant name 0)`

Any idea?

**Comment by dannytip** [comment]
@aljoshagasser how did you get the indexes working correctly? i'm having the same issue.

**Comment by aljoshagasser** [comment]
Hello @dannytip 

As I mentioned already I've added the following method to my Feedback model, which caused my fields to be generated properly including the correct index:

```
def feedback_answers_attributes=(attributes)
end
```

However I wasn't able to submit the form properly and so I came up with the following solution for my **create** action in my **FeedbacksController**:

```
class FeedbacksController < Application Controller
...
  def create
    @feedback = Feedback.post(nil, {}, {feedback: feedback_params}.to_json)

    if @feedback.kind_of? Net::HTTPSuccess
      redirect_back(fallback_location: root_path, flash: { success: t('feedback.success') })
    end
  end
...
end
```

I honestly don't know if that's the way to do it but it worked for me so I'm happy for now.

Good luck!

**Comment by dannytip** [comment]
Thanks i managed to get something working.  Handling validation was a nightmare, i will post a gist when i get a moment.

**Comment by dannytip** [comment]
I also had to monkey patch `custom_method_collection_url` to allow me to post to the standard create route.

**Comment by mltsy** [comment]
I've been struggling with the same issues (`wrong constant name: 0`), but this is a result of trying to call `.new` (or `update_attributes`, which calls `new`) on an ActiveResource model.  Rather than having it create a new instance automatically and save that for you, try using the `attributes=` method to set the attributes, and then save the model manually:

```ruby
  feedback.attributes = feedback_params.merge(id: feedback.id) # attributes= overwrites the id param... silly method
  if feedback.save
    flash[:success] = ...
  else
    flash[:errors] = ...
  end
```

This circumvents the issue of trying to create a new ActiveResource model from a Hash of attributes that aren't all nested models.  It should pass your `feedback_answers_attributes` attribute through to the API endpoint unchanged.

**Comment by aljoshagasser** [comment]
Thanks @mltsy ! That did it for me.

**Comment by jeremy** [comment]
Quite a struggle! Thanks all for chiming in. Pull requests welcome to help clarify, support, and document nested form handling with Active Resource. ❤️
