### ISSUE TITLE
Custom methods don't seem to work properly 

### ISSUE THREAD

**Issue by jcohenho** [rails/activeresource#273]
I try running queries like Person.find(1).get(:shallow) against custom routes, but the custom element is always ignored. Instead, the route that is hit is `/person/1.json` intead of `/person/1/shallow.json`. The routes described [here](http://www.rubydoc.info/gems/activeresource/ActiveResource/CustomMethods) also seem outdated. Is there newer documentation on how to write custom methods?

**Comment by imnotquitejack** [comment]
Has anyone identified a resolution for this?

**Comment by noctivityinc** [comment]
Is this gem even supported anymore?

**Comment by rafaelfranca** [comment]
Kinda of. It isn't part of Rails since Rails 5.0, so it will receive less and less support over time. Only critical bugs are being fixed, but we will gladly merge any pull request that fix other bugs. We will just not be focusing in fixing bugs that don't affect our applications.

**Comment by noctivityinc** [comment]
@rafaelfranca you really should add a note that this is not actively supported.  Given Rails 7 focus on supporting API mode, what is the current recommended gem to consume RESTful APIs?  I dont think httparty is being actively maintained either.  Seems insane that there is all this work going towards creating RESTful APIs but not consuming them.

**Comment by rafaelfranca** [comment]
But in any case, we have tests for this and it is passing https://github.com/rails/activeresource/blob/main/test/cases/base/custom_methods_test.rb#L77. So if you having problems please let us know how to reproduce the problem.

**Comment by rafaelfranca** [comment]
> what is the current recommended gem to consume RESTful APIs?

We don't have any recommended gem to consume RESTful APIs. We stoped recommending any gem for doing that when Active Recources was removed from Rails years ago.

**Comment by rafaelfranca** [comment]
> Given Rails 7 focus on supporting API mode

Also, are you sure about this? Rails 7 is mostly about HTML over the wire, not API applications.

**Comment by rafaelfranca** [comment]
> you really should add a note that this is not actively supported.

But it is actively supported. It is just we only support what we care about. If you want support for your own issues, please open PRs, we are gladly going to merge.

**Comment by noctivityinc** [comment]
@rafaelfranca Yes, I would say being able to rapidly build and API has been a focus since Rails 5.2.  See https://guides.rubyonrails.org/api_app.html.  



> 

@rafaelfranca Yes, I would say being able to rapidly build and API has been a focus since Rails 5.2.  See https://guides.rubyonrails.org/api_app.html.

**Comment by noctivityinc** [comment]
@rafaelfranca right now the issues we are having is that custom methods do NOT return a hash of the response like other methods.  So if we have a custom method called `refresh_key` in our API and we try something like: 

```User.find(1).put(:refresh_keys)```

We get a 200 response but the json representation returned by the API is not returned as a hash the same way it is when you do create or find.  We need to do ```JSON.parse(response)``` to access the response.  Which doesnt make sense and isnt documented anywhere.

**Comment by rafaelfranca** [comment]
That is not true. While Rails 5.2 introduced an API mode, it is not the focus of the framework. It was and always will to build full stack applications.



> right now the issues we are having is that custom methods do NOT return a hash of the response like other methods. So if we have a custom method called `refresh_key` in our API and we try something like:
> 
> `User.find(1).put(:refresh_keys)`
> 
> We get a 200 response but the json representation returned by the API is not returned as a hash the same way it is when you do create or find. We need to do `JSON.parse(response)` to access the response. Which doesnt make sense and isnt documented anywhere.

Got it. Like I said I'm happy to merge a PR to fix it. Please do investigate.

**Comment by noctivityinc** [comment]
@rafaelfranca I dont have a PR fix, I view this as a bug but since you arent actively maintaining or improving this gem, I guess it doesn't matter.

**Comment by rafaelfranca** [comment]
I'm not sure what is not clear here. The gem is actively maintained. Unless you only thing gems where the maintainer work for free for you to investigate your issues is the only definition of actively maintained.

Each people have different priorities. Fixing custom methods is not a priority for me because I don't use them. If it is a priority for you, why can't you work on fixing it instead of asking me to fix it for you and telling me that if I don't do that the gem is not maintained?

I'm more than happy to review a PR, answer questions about the implementation you might have. I'm not going to fix something that is low priority for me and don't affect me. I have way more things to do.

**Comment by noctivityinc** [comment]
@rafaelfranca I didnt mean to offend you and think it's a great gem.  I completely understand what you are saying, however, to be frank if I build something and release it and it doesn't work as documented or intended I personally feel the responsibility is on me to fix the bug.  If it was an improvement, then yes, that's on the person who needs the functionality.  But if the intended functionality of a custom put or post request is to not return the response, then fine.  It's simply not documented is all.  Thanks again for the gem.

**Comment by rafaelfranca** [comment]
I think the problem is also, our tests are passing. Calling `User.find(1).put(:refresh_keys)` get us a hash there, so I'm not even sure how to reproduce the problem you are describing.

**Comment by rafaelfranca** [comment]
Ah, BTW, no offence taken and I also get where you coming from. The problem is that this gem is very low priority over other parts of Rails, so unless we have easy ways to know what problems people are having we will most likely find another thing with more priority to work on.

**Comment by noctivityinc** [comment]
> I think the problem is also, our tests are passing. Calling `User.find(1).put(:refresh_keys)` get us a hash there, so I'm not even sure how to reproduce the problem you are describing. If you could at least open an issue with steps to reproduce that would help, not me, but anyone else to fix this bug.

Oh that's interesting.  It's working for you?  Ill need to dig into that a bit to see whats up.  Our refresh method is stupid simple:

```
  def refresh
    render json: @user_key.refresh!, status: :ok
  end
```

so not sure what's up.  Ill dig around a little.  I wonder if it has to do with how we are calling it `user_key = UserKey.put(:refresh, id: self.key)` instead of using the find first, which saves us an extra call.
