### ISSUE TITLE
Changing headers on base class doesn't change them in subclasses

### ISSUE THREAD

**Issue by mltsy** [rails/activeresource#277]
Given models like:

```ruby
ApiModel < ActiveResource::Base
  self.site = "http://api.some-site.com"
end

Project < ApiModel
  belongs_to :cluster
end

Cluster < ApiModel
  has_many :projects
end
```

I want to be able to set authentication headers per request, to use OAuth for authentication.  I thought this was possible (it was working, until I logged in with two different users) by just updating the headers:

```ruby
before_action do
  ApiModel.headers['Authorization'] = "Bearer #{...request.something...}"
end
```

But in the case of headers, [calling the reader on a subclass sets the headers permanently for that subclass](https://github.com/rails/activeresource/blob/master/lib/active_resource/base.rb#L664).  This, to me, seems unintuitive given the fact that all connection options are inherited from the base class to begin with.  It seems that I should be able to change them on the base class, and they should be used in all subclasses where they haven't been explicitly overridden.

Is there a recommended way to update headers on all the objects that inherit from `ActiveResource::Base` without cycling through and updating every one?  Would you be against changing the `headers` reader to avoid setting `_headers` on the subclass, and just return the merged headers (`superclass.headers.merge(headers_state)`) every time so that if a header is changed on the superclass, it will be always be returned when calling `.headers` on a subclass unless explicitly overridden?

This would be more analogous to how `site` and `proxy` are handled, from what I can tell. There is no merging happening in those cases, but the important part is that the attribute is never set in the readers, so if it is changed on the superclass, that change is reflected in the subclasses that haven't overridden a given attribute.

**Comment by mltsy** [comment]
I just realized why it's (probably) done like it is - because of the writer (`[]=`) - we don't want setting headers in a subclass to be updating headers in the base class.

So I guess this would actually require creating a new class for headers, like `InheritedHash` or something that could override the `[]=` operator so that it would *set* values on the subclass's copy, while reading variables from the merged result.  Not so bad though, for the flexibility it allows!

**Comment by jeremy** [comment]
Agreed that copy-on-read headers are surprising.

Here's an approach that adds native bearer token support to ActiveResource::Connection itself:
```ruby
module BearerTokenAuthorization
  def self.prepended(base)
    base.attr_accessor :bearer_token
  end

  def authorization_header(http_method, url)
    if bearer_token
      { 'Authorization' => "Bearer #{bearer_token}" }
    else
      super
    end
  end

  private
    def legitimize_auth_type(auth_type)
      auth_type == :bearer or super
    end
end

ActiveResource::Connection.prepend BearerTokenAuthorization

# To manage auth:
def self.with_bearer_token(token)
  self.connection.auth_type = :bearer
  self.connection.bearer_token = @access_token
  yield
ensure
  self.connection.auth_type = nil
  self.connection.bearer_token = nil
end
```

**Comment by lucasklaassen** [comment]
@mltsy what did you end up going with here?

**Comment by mltsy** [comment]
And I can't recall the solution I ended up using unfortunately (no longer have access to the project), but that recommendation seems like a reasonable place to start :)

**Comment by lucasklaassen** [comment]
@jeremy @mltsy thanks guys! PR up: https://github.com/rails/activeresource/pull/299

**Comment by adrien-k** [comment]
This is an old issue but somehow we stubbled on it today :).
The fix does not look that complex, or I might be missing something with thread?
Proposed PR: https://github.com/rails/activeresource/pull/359

Also, if not fixed, it would be worth updating the README as the implication are rather serious: leaking session tokens between requests.

```
# README.md
You can also set any specific HTTP header using the same way. As mentioned above, headers are thread-safe, so you can set headers dynamically, even in a multi-threaded environment:
```
ActiveResource::Base.headers['Authorization'] = current_session_api_token
```

**Comment by adrien-k** [comment]
Just refreshing this thread as my PR got marked as stale.

This is quite a serious issue, as shown by the following example:

If we consider this simple model:
```ruby
ApiModel < ActiveResource::Base
  self.site = "http://api.some-site.com"
end
```

Now the API handles two requests, on the same thread, for two users, with different credentials:

```ruby
(...)
# The controller sets the header based on current user, Bob
ActiveResource::Base.headers['Authorization'] = "Bob's TOKEN"

(...)
# And then makes a an active resource request, with bob's credentiels
ApiModel.find(1) 

# Later on, a request from Alice, on the same thread, sets the header again
ActiveResource::Base.headers['Authorization'] = "Alice's TOKEN"

# but...the request is still made with Bob's credentials, as ApiMode did read the header and kept a stale copy of it!!!
ApiModel.find(1) 
```

**Comment by bettysteger** [comment]
i've got the same problem as @adrien-k !!

@adrien-k do you still have the problem, or do you have a fix?

**Comment by mltsy** [comment]
It looks like [adrian-k's fix](https://github.com/rails/activeresource/pull/359) got [merged into v6.0](https://github.com/rails/activeresource/commit/366604d10a975bc7ff1b3e80c5822fee138ddbb1) and the problem should be solved there - what version are you on?

**Comment by bettysteger** [comment]
> It looks like [adrian-k's fix](https://github.com/rails/activeresource/pull/359) got [merged into v6.0](https://github.com/rails/activeresource/commit/366604d10a975bc7ff1b3e80c5822fee138ddbb1) and the problem should be solved there - what version are you on @bettysteger 

@mltsy i am on  activeresource (6.1.4)

**Comment by edolix** [comment]
Hey all, i got the same issue with this in the `ApplicationController`:

```rb
before_action :set_active_resource_authorization
...
def set_active_resource_authorization
  ActiveResource::Base.headers["Authorization"] = "Bearer #{current_user.token}"
end
```

And i solved it using a [Current Attribute](https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html) and `auth_type` and `bearer_token` on my parent `ApplicationResource`.

> app/controllers/application_controller.rb
```rb
before_action :set_active_resource_authorization
...
def set_active_resource_authorization
  Current.token = current_user.token
end
```

> app/models/current.rb
```rb
class Current < ActiveSupport::CurrentAttributes
  attribute :token
end
```

> app/resources/application_resource.rb
```rb
# base class that all other resources will inherit from
class ApplicationResource < ActiveResource::Base
  self.site = "https://domain.example"
  self.prefix = "/api/v1/"
  self.element_name = ""
  self.format = :json
  self.include_format_in_path = false

  self.auth_type = :bearer
  # Override bearer_token getter to read from CurrentAttribute
  def self.bearer_token
    Current.token
  end
end
```

I'm not _excited_ by the solution because of the `bearer_token` override and the Current attribute but... it works!

**Comment by bettysteger** [comment]
@edolix when setting the bearer token, it works for me just by setting 

```
ApplicationResource.connection.bearer_token = token
```
before making the request!

the model 

```
class ApplicationResource < ActiveResource::Base
  self.site = "https://domain.example"
  self.prefix = "/api/v1/"
  self.element_name = ""
  self.format = :json
  self.include_format_in_path = false
  connection.auth_type = :bearer
end
```

**Comment by bettysteger** [comment]
I have the problem that the header does not update: 

```
class ApplicationResource < ActiveResource::Base
  self.site = 'https://domain.example' # will be overridden by the actual site
  # @see https://github.com/rails/activeresource?tab=readme-ov-file#authentication
  headers['Authorization'] = nil

  def self.client_authorize(company)
    creds = company.example_credentials # has url and token
    return if creds.nil? || creds['url'].nil? || creds['token'].nil?

    puts '---------------'
    puts creds['token'] # NEW token
    puts '---------------'
    self.site = creds['url'] # this works
    # uses old headers, when updated -- why?
    ApplicationResource.headers['Authorization'] = "Token #{creds['token']}"
    puts '---------------'
    puts "Token #{creds['token']}" == headers['Authorization'] # true
    puts '---------------'
    "Token #{creds['token']}"
  end
end
```

**Comment by edolix** [comment]
Sorry @bettysteger, just to clarify, if you're setting the bearer token with:

```rb
ApplicationResource.connection.bearer_token = token
```

do you need to set `headers['Authorization']` as well?

**Comment by bettysteger** [comment]
> Sorry @bettysteger, just to clarify, if you're setting the bearer token with:
> 
> ```rb
> ApplicationResource.connection.bearer_token = token
> ```
> 
> do you need to set `headers['Authorization']` as well? 

No!
