### ISSUE TITLE
Feature Request: Default Prefix

### ISSUE THREAD

**Issue by BMannell** [rails/activeresource#279]
I'm have a situation where it would be convenient to have a default prefix inserted into all request paths. 
The API I am accessing is structured like so: `http://www.domain.com/api/v1/`. 
Setting the prefix variable of Base to `/api/v1/` is a good solution to add the API path to all requests, however the prefix variable is overwritten when trying to request a associated records. 

Example
```ruby
person = Person.find(1) # => calls /api/v1/persons/1
person.orders # => calls /persons/:person_id/orders
```

Desired Behaviour
```ruby
person = Person.find(1) # => calls /api/v1/persons/1
person.orders # => calls /api/v1/persons/:person_id/orders
```

Being able to set a default prefix would be very beneficial. 

Current workaround. This works for collections but breaks singular requests.
```ruby
class Order < ActiveResource::Base
  belongs_to :person
  self.prefix = '/api/v1/persons/:person_id/'
end

person = Person.find(1)
person.orders # => api/v1/persons/1/orders

Order.find(1) # => ActiveResource::MissingPrefixParam: person_id prefix_option is missing
```

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
