### ISSUE TITLE
Documentation for associations is wrong

### ISSUE THREAD

**Issue by jasonkarns** [rails/activeresource#280]
This is related to #16 and #17.

Specifically, the [readme states](https://github.com/rails/activeresource/blob/master/README.rdoc#associations) that `has_many` assocations will generate nested resource requests:

> comments = post.comments # issues GET http://blog.io/posts/1/comments.json

However, [per the code](https://github.com/rails/activeresource/blob/d9124b9907d2a61781b0111a2ab00afc22c79e4a/lib/active_resource/associations.rb#L150), it is generating a top-level resource request, using the foreign_key as query param.

```ruby
instance_variable_set(ivar_name, reflection.klass.find(:all, :params => {:"#{self.class.element_name}_id" => self.id}))
```

**Comment by jeremy** [comment]
#281
