### ISSUE TITLE
protected method `update' called for #<Project:0x00007fdc9479d3a8>

### ISSUE THREAD

**Issue by jpavanaryan** [rails/activeresource#282]
I set up simple Rails application with JHipster microservices. The application has a `Project` model class and CRUD operations on it. JHipster microservices with REST API support, integrated with Rails application and Create, Destroy, Show operations are working fine. But update operation throws following error. All the code uploaded to [github repository](https://github.com/jpavanaryan/dockerapps). I looked at similar issues but could not find a proper solution.

`protected method 'update' called for #<Project:0x00007fdc9479d3a8>`

![screenshot from 2018-02-13 15-31-03](https://user-images.githubusercontent.com/17564080/36172234-3a8abef4-10d3-11e8-9366-4db0fcecf949.png)

projects_controller.rb
```

class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update_attributes(project_params)
    load(project_params, false) && save
  end


  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :location)
    end
end

```

**Comment by jeremy** [comment]
Active Resource still uses the old `update_attributes` API.

**Comment by jpavanaryan** [comment]
Can I use `update` method with old version of Rails i.e 4.2? Or I should use only `update_attributes` method?

**Comment by jeremy** [comment]
Cool, Active Resource is issuing the request you expect, then. A troubleshooting dive into how your backend service is actually behaving in practice (documented or not) is the next step!

**Comment by lancecarlson** [comment]
@jeremy Do you think that we should start migrating to the update method API? If this is what Rails 5 expects when generating ActiveRecord models, I think it should be made consistent here too. We should add a deprecated flag on the usage of update_attributes as well.
