### ISSUE TITLE
Railtie initializer runs before Rails.application.configure block

### ISSUE THREAD

**Issue by jasonkarns** [rails/activeresource#288]
Given an active_resource initializer:
```
Rails.application.configure do
  config.active_resource.logger = Rails.logger
end
```

The railtie initializer (`active_resource.set_configs`) https://github.com/rails/activeresource/blob/bc2dd80e26b408086e8814ec81d596f106d110c7/lib/active_resource/railtie.rb#L9-L11 runs before the block in our app's config/initializers/active_resource.rb (shown above).

I believe this is because the `active_resource.set_configs` initializer isn't wrapping its block in `ActiveSupport.on_load(:active_resource)`.

When I modified the gem to wrap the initializer, then the initializer ran in the correct order (ie, after our app's initializer had a chance to set config options.

This is consistent with how the ActiveRecord railti runs its initializers (ie, they're all wrapped in `ActiveSupport.on_load(:active_record)` )

**Comment by rafaelfranca** [comment]
Yes. That is correct, we should be using `on_load`. Mind to open a PR?
