### ISSUE TITLE
Custom from_json on Errors

### ISSUE THREAD

**Issue by lancecarlson** [rails/activeresource#291]
There should be an easy way for one to override a model's from_json to errors. There may be some API's that return something as subtle as a "error": instead of "errors": in the error return result. It would be nice to be able to easily map your models to the service's return.

**Comment by rafaelfranca** [comment]
Thank you so much for the issue but we don't take feature request on the issue tracker. We recommend you to try to implement the feature and send us a pull request or if you are in doubt if the feature will be accepts ask in Rails Core mailing list for feedback.
