### ISSUE TITLE
Associations between ActiveResource and ActiveRecord

### ISSUE THREAD

**Issue by maurosbu** [rails/activeresource#292]
Is there a way to create associations between ActiveResource models and ActiveRecord ones?
I tried to add a belongs_to association and I got the following error:

    NoMethodError (undefined method `arel_table' for Project:Class)

Many thanks.
Mauro

**Comment by rafaelfranca** [comment]
No. There is no way to create Active Record associations between models that are not Active Record models.

**Comment by maurosbu** [comment]
@rafaelfranca I can easily define methods on local resources in order to be able to load remote ones, but then I have N+1 query problems when working with collections.  

Example: a collection of local resources (AR), each one belonging to a remote one (ARes)
How would you avoid this?

Many thanks,
Mauro

**Comment by basicBrogrammer** [comment]
I created a PR that demonstrated a potential implementation for a `belongs_to_resource` relationship. This could also be pulled out into a stand alone gem or left as a module that does not patch ActiveRecord upon initialization. https://github.com/rails/activeresource/pull/393
