### ISSUE TITLE
Would you guys mind cutting a new version of the gem?

### ISSUE THREAD

**Issue by abelmartin** [rails/activeresource#295]
Hey all,

Since: 
1. the master branch is so far ahead of the last 5.0.0 release
1. there are no issues, just a few PRs
1. installation instructions for 5.0.0 say users should reference `master`
1. it's been over a year since the 5.0.0 release

...would you mind cutting a new gem?  Is a reason you guys are holding back?

**Comment by rafaelfranca** [comment]
Thank for the issue! The release will be real soon ™️

**Comment by abelmartin** [comment]
We should probably reopen this ticket until you cut a new gem.

**Comment by rafaelfranca** [comment]
I don't think we need to. Releasing the gem is not an issue, you as an user can always use the github repository. Releasing the gem is part of the maintenance activities and when it is going to be done if up to the maintainers.

**Comment by abelmartin** [comment]
This would have been a more helpful response when I originally opened my issue.  I realize releasing the gem is part of the maintenance activity, but that maintenance hasn't been done in a very long time.  Is there any update on when another gem will be cut?

**Comment by rafaelfranca** [comment]
No. Really soon. Maybe some time last week, maybe in two weeks. I need to review a PR and that is the only thing blocking it now. I'll try to do next week.
