### ISSUE TITLE
Cannot levearge ActiveModel::Dirty methods in ActiveResource models

### ISSUE THREAD

**Issue by vasudharsai** [rails/activeresource#308]
Hi
I'm not able to leverage the methods that come with ActiveModel:Dirty module in classes inherited from ActiveResource. I tried including ActiveModel::Dirty in ActiveResource classes but still it doesn't work. Is there any work around to access these methods in Active Resource inherited objects?

**Comment by rafaelfranca** [comment]
Unfortunately there is no support to dirty methods in Active Resource.
