### ISSUE TITLE
Attribute clash in case of ResourceInvalid exception

### ISSUE THREAD

**Issue by andrisbriedis** [rails/activeresource#309]
[Shopify API gem](https://github.com/Shopify/shopify_api) has a model, that inherits from `ActiveResource::Base` and contains a property `code`. No other modifications are done to the class.

If `save!` method call results in a status code `422`, then the resulting `ResourceInvalid` exception contains code value from the model's attribute, not `422` as I would expect.

The error message looks like this:
```
ActiveResource::ResourceInvalid - Failed.  Response code = my-discount-code. Code: must be unique. Please try a different code.
```

In this particular case the model is a part of Shopify API, so renaming it is not an option.

Here are the http logs:
```
[httplog] Sending: POST http://test-shop.myshopify.com:443/admin/price_rules/123456789/discount_codes.json
[httplog] Data: {"discount_code":{"code":"my-discount-code"}}
[httplog] Status: 422
[httplog] Benchmark: 0.29564 seconds
[httplog] Response:
{"errors":{"code":["must be unique. Please try a different code."]}}
```
I was not sure where to put this (in shopify API repo or here), so I registered it in both places. Here is the link to Shopify API issue I created: https://github.com/Shopify/shopify_api/issues/558

**Comment by rafaelfranca** [comment]
I'm having a really hard time to understand how this is possible `response` is a `Net::HTTPResponse` and it doesn't expose the body as arguments as methods. Are you able to reproduce this without `shopify_api`?

**Comment by rafaelfranca** [comment]
What is even stranger is that if `response.code` was returning `my-discount-code` the exception raised would not be `ResourceInvalid` but `ConnectionError`, since `response.code.to_i` would be `0`. See https://github.com/rails/activeresource/blob/5ca794b7d12d60e7db7171b9364ba83c45e8ccdf/lib/active_resource/connection.rb#L134-L167.

**Comment by andrisbriedis** [comment]
Hi, @rafaelfranca. Thank you for the response!
I will try to reproduce it without shopify. Meanwhile, here is an rspec test I use to reproduce the issue:
```
describe ShopifyAPI::DiscountCode do
  it('should properly handle error status') do
    WebMock.stub_request(:post, %r{.*\/admin\/price_rules\/\d+/discount_codes.json.*})
      .to_return(status: 422, body: '{"errors":{"code":["must be unique. Please try a different code."]}}')

    session = ShopifyAPI::Session.new('test.myshopify.com', 'test-token')
    ShopifyAPI::Base.activate_session(session)

    discount = ShopifyAPI::DiscountCode.new(code: 'my-discount-code', price_rule_id: 123)

    expect{discount.save!}.to raise_error(ActiveResource::ResourceInvalid) do |error|
      expect(error.response.code).to eq(422)
      expect(error.message).to eq('Failed.  Response code = 422.')
    end
  end
end

```

**Comment by andrisbriedis** [comment]
Ok, here is a test without shopify:
```ruby
  class Example < ActiveResource::Base
    self.site = "http://api.example.com:3000"
  end

  it('should properly handle error status without shopify') do
    WebMock.stub_request(:post, 'http://api.example.com:3000/examples.json')
      .to_return(status: 422, body: '{"errors":{"code":["must be unique. Please try a different code."]}}')

    example = Example.new(code: 'my-discount-code')

    expect{example.save!}.to raise_error(ActiveResource::ResourceInvalid) do |error|
      expect(error.response.code).to eq(422)
    end
  end
```

Found an interesting code in `ActiveResource::Base` `save!` method:
```ruby
    def save!
      save || raise(ResourceInvalid.new(self))
    end
```
I guess that explains the issue because the constructor of the ResourceInvalid is supposed to take a network response, not the activeresource itself. The problem is that at this point we don't have the original response anymore.

**Comment by rafaelfranca** [comment]
Thanks! That makes sense. I'll take a look.

**Comment by marisveide** [comment]
Hello, @rafaelfranca !
How does it look like?
Really waiting for a solution here, we have this issue coming up quite often...

Thank you so much for taking this...

**Comment by marisveide** [comment]
If only we knew how to fix this...

**Comment by marisveide** [comment]
Following up on this - is it really not an issue for anybody else?

**Comment by alexmamonchik** [comment]
it is! That's really problem.
