### ISSUE TITLE
Connection Pooling Enabled?

### ISSUE THREAD

**Issue by cjekal** [rails/activeresource#314]
I had a beginner-level question. I'm looking for a good REST client to use and while I've heard good things about RestClient/HTTParty, I've read that they don't support connection pooling, which can make a huge difference over HTTPS connections (and I plan on making many requests over HTTPS). Does ActiveResource support connection pooling? If so, how do I configure?

**Comment by rafaelfranca** [comment]
Active Resource uses Ruby's `Net::Http`. if `Net::Http` support connection pooling Active Resource will support as well.

**Comment by Ashaba** [comment]
If connection pooling is a crucial requirement for your application, it would be advisable to consider switching to a library like `Typhoeus` or exploring other options that provide connection pooling capabilities.
