### ISSUE TITLE
Labels translations in forms

### ISSUE THREAD

**Issue by patriciobi** [rails/activeresource#316]
According to [FormHelper's documentation](https://api.rubyonrails.org/v5.1/classes/ActionView/Helpers/FormHelper.html) 

> the text of label will default to the attribute name unless a translation is found in the current I18n locale (through helpers.label.<modelname>.<attribute>) or you specify it explicitly.

So if I have:

```
activerecord:
  attributes:
    user:
      name: 'Nombre'
```

and a:

`<%= form_for @user...`

It will automatically translate the `name` label, but this doesn't seem to work with activeresource, is there a way to do this and not have to write the full `t('activeresource.attributes.user.name')`, for example?

**Comment by rafaelfranca** [comment]
No. Active Resource was not made to be used with forms automatically.
