### ISSUE TITLE
Custom validations called twice.

### ISSUE THREAD

**Issue by oatw** [rails/activeresource#318]
Validation callbacks are already called in `ActiveModel::Validations#valid?` 

https://github.com/rails/rails/blob/f7049ec583a727c72ee7b218fbff267a06cd7882/activemodel/lib/active_model/validations.rb#L337

![image](https://user-images.githubusercontent.com/47649745/63742962-2ec4a180-c8cd-11e9-9b92-ed8723f6b8aa.png)

But `ActiveResource::Validations#valid?` calls both validation callbacks and `super`.

https://github.com/rails/activeresource/blob/ea6f109592d97966f339a38796e2a97c1eb1dd2f/lib/active_resource/validations.rb#L164

https://github.com/rails/activeresource/blob/ea6f109592d97966f339a38796e2a97c1eb1dd2f/lib/active_resource/validations.rb#L165

This causes custom validations called twice when `ActiveResource::Validations#valid?` called.

Is this an expected behavior or a bug?

Thanks for reading!

**Comment by meanphil** [comment]
Also just noticed this, although it doesn't seem to cause any practical issues, it did waste some time investigating the backtraces...
