### ISSUE TITLE
How to do pagination with ActiveResource?

### ISSUE THREAD

**Issue by twnaing** [rails/activeresource#327]
API response is always paginated and includes pagination information in response header as follows

```
Current-Page: 1
Link: <http://127.0.0.1:5000/api/v1/sites.json?page=1>; rel="first", <http://127.0.0.1:5000/api/v1/sites.json?page=2>; rel="next", <http://127.0.0.1:5000/api/v1/sites.json?page=6>; rel="last"
Page-Items: 15
Total-Count: 80
Total-Pages: 6
```

Is there a way to get the header using ActiveResource? (I found out that I can use lower level library like Faraday to get access to the header. But ActiveResource has all the feature I need except this one and I am reluctant to re-write most of ActiveResource in Faraday.)

Or is there any other approach I should do?

**Comment by rafaelfranca** [comment]
By default Active Resource don't know how to deal with those headers. You will need to implement it in your code.
