### ISSUE TITLE
How to make conditional endpoint?

### ISSUE THREAD

**Issue by arrowcircle** [rails/activeresource#328]
Hi!

I am trying to do conditions on endpoint.
Is it possible to make something like this?

```ruby
class Posts < ActiveResource
...
  def endpoint_suffix
    return '/v1/users/:user_id/posts' if params[:user_id].present?
    '/v1/posts'
  end
end
```

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
