### ISSUE TITLE
Make alias_attribute play nicely

### ISSUE THREAD

**Issue by glennfu** [rails/activeresource#340]
```
class Staff < ActiveResource::Base
  alias_attribute :email, :Email
end
```

I have an external resource that uses CamelCased attributes, like above. If I try to create my own using `:email`, I run into trouble:

```
s = Staff.new
=> #<Staff:0x000055cc7c40ae40 @attributes={}, @prefix_options={}, @persisted=false>
s.email = "asdf"
=> "asdf"
> s.email
Traceback (most recent call last):
       12: from bin/rails:4:in `<main>'
       11: from bin/rails:4:in `require'
        ...
        2: from /usr/local/bundle/gems/activemodel-5.0.7.2/lib/active_model/attribute_methods.rb:433:in `method_missing'
        1: from /usr/local/bundle/gems/activeresource-5.1.1/lib/active_resource/base.rb:1678:in `method_missing'
NoMethodError (undefined method `Email' for #<Staff:0x000055cc7c40ae40>)
```

The `method_missing` that handles this mapping in ActiveResource looks like:
```
  def method_missing(method_symbol, *arguments) #:nodoc:
    method_name = method_symbol.to_s

    if method_name =~ /(=|\?)$/
      case $1
      when "="
        attributes[$`] = arguments.first
      when "?"
        attributes[$`]
      end
    else
      # puts "method_name: #{method_name}, attributes: #{attributes.inspect}"
      return attributes[method_name] if attributes.include?(method_name)
      # not set right now but we know about it
      return nil if known_attributes.include?(method_name)
      super
    end
  end
```

Changing that `when "="` to this solves my problem:
```
      when "="
        key = self.class.attribute_alias($`) || $`
        attributes[key] = arguments.first
```

Would a PR with something like this be appropriate here, or should I just keep it for my project? Thanks!

**Comment by elbowdonkey** [comment]
I'd recommend handling it within your project. I think the scenario you describe is probably an edge case. I say this without any authority, but my guess is that most users of `ActiveResource` are working with Rails API apps (or full Rails apps with APIs). In the "normal" scenario, a proper-camelcased attribute isn't likely to happen.

If I were solving this in my app, instead of modifying the behavior of `ActiveResource` I'd modify the behavior of my own application. Something like:

```
module CamelcaseAlias
  def alias_camelcase_attribute(new_name, old_name)
    module_eval <<-STR, __FILE__, __LINE__ + 1
      def #{new_name}
        self.#{old_name}
      end
      def #{new_name}?
        !self.#{old_name}.nil?
      end
      def #{new_name}=(v)
        self.#{old_name} = v
      end
    STR
  end
end


class Staff < ActiveResource::Base
  extend CamelcaseAlias
  alias_camelcase_attribute(:email, :Email)
end
```

The idea here is that rather than making ActiveResource conform to your possibly edge-case scenario, have your app conform to ActiveResource. Note that while I tested this against a real Rails API, I can't say for sure if it's the perfect solution.

And this isn't the only way to do what I describe - defining your own methods like `def email; self.Email; end` probably work just as well. Odds are though, `Email` isn't the only one of these you encounter.

**Comment by glennfu** [comment]
My intention here was to add support to `alias_attribute`, which is a native Rails module. Since ActiveResource is made for people who use Rails, but may or may not connect to a Rails API, it seems to make sense to me to add support for this. I think it's more surprising to say, "ActiveResource was built for Rails, but not ALL of Rails".

As more food for thought I could just as reasonably have this as my Staff:
```
class Staff < ActiveResource::Base
  alias_attribute :email, :Email
  alias_attribute :full_name, :CustomerFirstLastSuffix
  alias_attribute :staff_id, :Representative_Number
end
```

A simple CamelCaseAlias wouldn't solve this. Also important for ActiveResource is the ability to serialize the record back into the attribute format that the API expects. `alias_attribute` provides hooks into reversing the attribute mapping, which is necessary for that. To get that whole set of functionality I would come close to having to re-implement all of `alias_attribute`. Luckily I don't need to since it's a stock Rails feature.

**Comment by elbowdonkey** [comment]
@glennfu I'm convinced. `alias_attribute` should work exactly like it does in any other Rails app.

That said, I just tried to recreate the behavior you're seeing, and I'm not seeing the same thing it.

ActiveResource is 5.1.1, but both `ActiveModel` and `ActiveResource` are version `5.2.4.3` (which means this test is using Rails 5.2.4.3). I suspect you're using Rails 5.0.7.2?

Here's what I did to test:

I setup my class:

```
class Staff < ActiveResource::Base
  alias_attribute :email, :Email
end
```

Then I try to recreate your issue in my client app Rails console:

```
staff = Staff.new
staff.attributes # => returns `{}` as expected
staff.email = "123"
staff.attributes # => returns `{"Email" => "123"}` as expected
staff.email # => returns "123" without throwing an exception
```

Even if I try to hit the old method, I have no issues:

```
staff.Email #=> returns "123"
```

I haven't looked at differences between versions yet but maybe updating to Rails 5.2.4.3 will allow `alias_attribute` to work as expected?

**Comment by elbowdonkey** [comment]
I just tested again, except this time using Rails 5.0.7.2 and I still can't recreate the issue.

The closest I could get was doing:

```
class Staff < ActiveResource::Base
  alias_attribute :email, :Email
end

s = Staff.new
s.email = "123"
s.email # => returns "123", no exception thrown
s.Email # => returns "123", no exception thrown

s = Staff.new
s.email


NoMethodError: undefined method `Email' for #<Staff:0x00007fbfd712bad0>
Did you mean?  email=
               email?
from /usr/local/var/rbenv/versions/2.6.5/gemsets/alias_attributes_test/gems/activeresource-5.1.1/lib/active_resource/base.rb:1678:in "method_missing"
```

So, I'm a bit stumped why your example throws an exception. Are you able to recreate it in a fully isolated way?

My test is literally just a Gemfile:

```
source "https://rubygems.org"

gem "activeresource", "5.1.1"
gem "rails", "5.0.7.2"
```

And a single ruby file:

```
require "activeresource"

class Staff < ActiveResource::Base
  alias_attribute :email, :Email
end
```

I then start `irb`, and do:

```
require_relative "staff"
s = Staff.new
s.email = "123"
s.email # => return "123"
```
