### ISSUE TITLE
Lazy loading for custom methods

### ISSUE THREAD

**Issue by chapmajs** [rails/activeresource#341]
I'm currently using the following to "lazy load" an ActiveResource model and call a custom method on it:

`Widget.new(:id => 'KnownValidId').patch(:approve)`

This results in a call to `https://project.domain/api/widgets/KnownValidId/approve.json` which is what I want. I want to avoid having to `find()` the Widget and I don't really want to put `approve` on the collection, since it's really a member function.

Is this something I'm missing in the documentation? If not, is a "lazy load" option for e.g. `find()` desirable and something a PR would be accepted on?

**Comment by elbowdonkey** [comment]
You're not missing anything in the documentation (as far as I know).

This is a bit of a hack, but you can do:

```
Widget.new.patch("#{id}/approve")
```

This will do `PATCH /api/widgets/KnownValidId/approve`.

It's not very different from your example, but trades the awkward feeling of initializing a model with an ID for the awkward feeling of passing a relative path with an ID. 

Support for being able to do `Widget.patch(1, :approve)` (or similar) would be nice too.

You could have something close now by doing:

```
class Widget < ActiveResource::Base
  def self.approve(id)
    new.patch("#{id}/approve")
  end
end
```

That could hold you over until you submit a PR that allows the `patch` method to do `patch(id, custom_method)` (in addition to what it used to do).

**Comment by PedroAugustoRamalhoDuarte** [comment]
It would be a great feature, update/destroy a record without doing a find request before
