### ISSUE TITLE
New release to fix URL parser warnings?

### ISSUE THREAD

**Issue by andyw8** [rails/activeresource#350]
With the release of Rails 6.1, we're seeing deprecation warnings relating to URI.parser, e.g. https://github.com/Shopify/shopify_api/issues/826

I see there are some unreleased commits in master relating to this, is there anything holding up a new release?

**Comment by andyw8** [comment]
cc @byroot

**Comment by rafaelfranca** [comment]
Thank you for the issue. A release will happen when it happens. For now you can use the master branch.

**Comment by tonydewan** [comment]
@rafaelfranca Do you have a timeline for when a new version of activeresource might get released, or what external contributors can do to help get one made?
