### ISSUE TITLE
`require': cannot load such file -- active_resource (LoadError) in Ruby on Rails 5

### ISSUE THREAD

**Issue by yaingnan** [rails/activeresource#351]
I run redmine_download.rb.
[  
**/usr/local/rvm/rubies/ruby-2.5.7/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- active_resource (LoadError)
 from /usr/local/rvm/rubies/ruby-2.5.7/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
 from /opt/redmine_download.rb:4:in `<main>'**  
] error occour.

**In redmine_download.rb,**
#!/usr/local/rvm/rubies/ruby-2.5.7/bin/ruby

require 'rubygems'
require 'active_resource'
require 'fileutils'

class Issue < ActiveResource::Base
	self.site = ENV["REDMINE_URL"]
	self.user = ENV["REDMINE_UPDATE_USER"]
	self.password = ENV["REDMINE_UPDATE_PASSWORD"]
end

**Comment by rafaelfranca** [comment]
This seems to be an issue with readmine. Make sure the gem is installed.
