### ISSUE TITLE
ActiveResource::ActiveJobSerializer is not registered

### ISSUE THREAD

**Issue by luk4s** [rails/activeresource#354]
in application with Rails 6.1.3 I try to pass ActiveResource instance as a argument to `perform` in ActiveJob. Unfortunetely it raise serialization error.
But in release version of activeresource is serialized
https://github.com/rails/activeresource/blob/master/lib/active_resource/railtie.rb
But I found that condition is never met => `app.config.active_job` did not include :custom_serializers.

I dig deeper into ActiveJob and I suggest change registration to:
```ruby
ActiveJob::Serializers.add_serializers ActiveResource::ActiveJobSerializer
```

Do oyu think that is valid issue? I will prepare PR... 🙂

**Comment by rafaelfranca** [comment]
https://github.com/rails/rails/blob/291a3d2ef29a3842d1156ada7526f4ee60dd2b59/activejob/lib/active_job/railtie.rb#L10

`app.config.active_job` definitely includes `:custom_serializers`.

I think you need to investigate why in your app you don't have that.

**Comment by luk4s** [comment]
OK, I dig more deeper. You are right, array is defined in `active_job`. But `ActiveResource::ActiveJobSerializer` is still not in `ActiveJob::Serializers.serializers`. Even in empty rails app (rails new ...)

Finally i found difference in code between `master` branch and released gem of `activeresource`.
In short: https://github.com/rails/activeresource/commit/3fbbef15c210b44d5b31e4ae9bab12de7e9510c3#diff-5bddb168eb3f657b2137a0416a2a4670a601ee8c5ed41cd0aacd01e4a95a83bc

Released version `5.1.1` contains `defined?` condition => which "always" return `nil` (because "defined? []"). 
If I use `master` branch, it works well. Same test I tried with "hard-code" change in installed gem.

**Comment by rafaelfranca** [comment]
I see. So we only need a release? If that is the case I can prepare one and close this issue.

**Comment by luk4s** [comment]
Yes, new release will resolve this 👍

**Comment by luk4s** [comment]
Hi @rafaelfranca , do you know when release is planned? This issue can be close with it...
thx

**Comment by luk4s** [comment]
Hi @rafaelfranca have you some release plan for next version ?

**Comment by JamesPaden** [comment]
@rafaelfranca I also need a new release. Any updates? Thanks!

**Comment by rafaelfranca** [comment]
6.0.0 released which fix this issue
