### ISSUE TITLE
Custom code before using an ActiveResource model

### ISSUE THREAD

**Issue by marino-mrc** [rails/activeresource#368]
Hello,
I have the following pseudo code:
```
if token is missing
  global_token_var = login_and_obtain_token
else
  if token is expired
    global_token_var = renew_token
  end
end
```

It is possible to apply this code to an ActiveResource model? How can I implement it?
Thanks.
Marco

**Comment by rafaelfranca** [comment]
Please use https://discuss.rubyonrails.org/ for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
