### ISSUE TITLE
Compatibility with Rails 7

### ISSUE THREAD

**Issue by fabianof** [rails/activeresource#372]
Hi guys. Any chance to add compatibility with Rails 7?

Currently release 5.1.1 has these dependencies in `activeresource.gemspec`:
```
...
s.add_dependency("activesupport", ">= 5.0", "< 7")
s.add_dependency("activemodel", ">= 5.0", "< 7")
s.add_dependency("activemodel-serializers-xml", "~> 1.0")
...
```

This gem is awesome.

**Comment by aergonaut** [comment]
There is #367, but it is not yet merged.

**Comment by rafaelfranca** [comment]
6.0.0 released which fix this issue
