### ISSUE TITLE
Active Resource 6 breaking change: can't share common headers anymore

### ISSUE THREAD

**Issue by fabianof** [rails/activeresource#376]
After PR #359 (I guess) has been merged, we can't define common headers on base classes and make them available to subclasses, as expected.

This way, each subclass must configure the same access token, for example, instead of using parent access token, which would not be very DRY.

Please take a look on following sample code (using fruits and apples just like ARes test cases).

```
# 5.1

fruit = Class.new(ActiveResource::Base)
apple = Class.new(fruit)

fruit.headers["key"] = "fruit-value"

fruit.headers # => {"key"=>"fruit-value"}
apple.headers # => {"key"=>"fruit-value"}

# 6.0

fruit = Class.new(ActiveResource::Base)
apple = Class.new(fruit)

fruit.headers["key"] = "fruit-value"

fruit.headers # => {"key"=>"fruit-value"}
apple.headers # => {}

```

Please note that if key was access token, for example, then subclasses couldn't get authorized, since apple.headers is empty.

**Comment by rafaelfranca** [comment]
I think you are seeing an empty header but if you try to access `apple.headers["key"]` you will find the value. Did you try that?

**Comment by fabianof** [comment]
Hi @rafaelfranca. Thanks for your fast response.

Yes, I find the value when manually accessing the key. However, the issue happens when ARes tries to fetch resources (e.g. `Apple.all`.

See for example line 1108 in `lib/active_resource/base.rb`:

```
format.decode(connection.get(path, headers).body)
```

Here it tries to connect using an empty `headers`.

**Comment by rafaelfranca** [comment]
Right, that is a problem indeed. This gem has very low priority for me, so if you want, you could try to fix this case so the values in headers are kept the same.

**Comment by fabianof** [comment]
Sure thing. Thanks for confirming that that is a problem.

**Comment by meanphil** [comment]
Just ran into this myself! See #383 - hopefully it's the right fix. I think subclassing Hash in the first place was probably not a good idea, but this solves it without reimplementing it.

**Comment by cgriego** [comment]
Still an issue.

**Comment by bellef** [comment]
This is still an issue for me, is there a way to tackle this?

**Comment by klyonrad** [comment]
@bellef I moved the modification of the headers into the sub classes and called `self.class.headers = `
