### ISSUE TITLE
Support for has_many extensions?

### ISSUE THREAD

**Issue by noctivityinc** [rails/activeresource#378]
Is there any way to support a `has_many` extension in AR?  For example, if you have the following:

```
class Question < ActiveResource::Base
   has_many :answers do 
     def correct
          where(correct: true)
      end
   end 
end class
```

Would allow for something like ```Question.first.answers.correct``` to be equivalent to ```Question.first.answers.where(correct: true)```

**Comment by rafaelfranca** [comment]
No. There is no way to do that. But you might be able to do similar things with 

```ruby
class Question < ActiveResource::Base
   has_many :answers

   def correct_answers
          answers.where(correct: true)
   end 
end
```
