### ISSUE TITLE
Custom methods not returning the body as a hash

### ISSUE THREAD

**Issue by noctivityinc** [rails/activeresource#380]
Maybe I'm missing something here but after talking to @rafaelfranca I wanted to check it out.  If this is not actually a bug I apologize, but if it is and work is needed, I can explore it.

I enhanced the custom methods test in the gem with the following:

```
@matz_manager = { person: { id: 1, name: "Matz", position: "Manager" } }.to_json

ActiveResource::HttpMock.respond_to do |mock|
     ...
      mock.put    "/people/1/promote.json?position=Manager", {}, @matz_manager, 200
end
```

And this test:

```
    person = Person.find(1).put(:promote, { position: "Manager" })
    assert_equal "Manager", person["position"]
```

If I understand how httpmock works, then the above SHOULD pass but instead I get:

```
Expected: "Manager"
Actual: nil
```

When I inspect the `person` object above, I am seeing the body:

```.#<ActiveResource::Response:0x000000010aba3ac8 @headers={"Content-Length"=>"54"}, @message="200", @body="{\"person\":{\"id\":1,\"name\":\"Matz\",\"position\":\"Manager\"}}", @code=200>```

But it's just not returned as a hash.  Before I did around I wanted to make sure I have the test case setup correctly.  Thanks.

**Comment by rafaelfranca** [comment]
Thanks 👍🏽 . That will help me to investigate

**Comment by noctivityinc** [comment]
@rafaelfranca no problem.  Ive been digging since I posted this and it looks like the root has something to do with the `instantiate_collection` method not being called or connected to custom methods.  Im assuming this is because if you are calling a custom method there is no guarantee that it would return the same object.

If I am right about that, it makes sense (though still should be documented, however, there should be an option or way to either specify as an option that you want the object returned or create an object from the response. My 2 cents.
