### ISSUE TITLE
ActiveResource::Base.headers is not threadsafe

### ISSUE THREAD

**Issue by niedfelj** [rails/activeresource#60]
Is there a reason to not use Thread.current to store the headers in a similar way as a lot of other Rails "constants", so we can do per-request headers that contain additional information?

**Comment by bellef** [comment]
@mltsy for what I understand, the fix [538588d](https://github.com/rails/activeresource/commit/538588ddba9ffc9bf356790e9186dc7e6adad12f) does not solve the problem @niedfelj pointed out.

Correct me if I'm wrong but I understand that it stores the `_headers` variable in `Thread.main` context and not in `Thread.current`, preventing a per-thread authorization.
