### ISSUE TITLE
Array response with hash which has only one key got an ArgumentError: expected an attributes Hash

### ISSUE THREAD

**Issue by Piioo** [rails/activeresource#86]
Hello,

this response work fine:

    [
        {
            "foo" : "foo",
            "title" : "bar"
        },
        {
           "foo" : "foo2",
           "title" : "baz"
        }
     ]

     [#<Theme:0x0000000655d998 @attributes={"foo"=>"foo", "title"=>"bar"}...]

but this one do not work:

    [
       {
          "title" : "bar"
       },
       {
          "title" : "baz"
       }
    ]

I got this:
ArgumentError: expected an attributes Hash, got "bar"
	from /home/pio/.rvm/gems/ruby-2.0.0-p247@werweisswas/gems/activeresource-4.0.0/lib/active_resource/base.rb:1328:in `load'
	from /home/pio/.rvm/gems/ruby-2.0.0-p247@werweisswas/gems/activeresource-4.0.0/lib/active_resource/base.rb:1075:in `initialize'
	from /home/pio/.rvm/gems/ruby-2.0.0-p247@werweisswas/gems/activeresource-4.0.0/lib/active_resource/base.rb:1002:in `new'
	from /home/pio/.rvm/gems/ruby-2.0.0-p247@werweisswas/gems/activeresource-4.0.0/lib/active_resource/base.rb:1002:in `instantiate_record'
	from /home/pio/.rvm/gems/ruby-2.0.0-p247@werweisswas/gems/activeresource-4.0.0/lib/active_resource/base.rb:998:in `block in instantiate_collection'
	from /home/pio/.rvm/gems/ruby-2.0.0-p247@werweisswas/gems/activeresource-4.0.0/lib/active_resource/collection.rb:67:in `block in collect!'
	from /home/pio/.rvm/gems/ruby-2.0.0-p247@werweisswas/gems/activeresource-4.0.0/lib/active_resource/collection.rb:7:in `each'
	from /home/pio/.rvm/gems/ruby-2.0.0-p247@werweisswas/gems/activeresource-4.0.0/lib/active_resource/collection.rb:7:in `each'
	from /home/pio/.rvm/gems/ruby-2.0.0-p247@werweisswas/gems/activeresource-4.0.0/lib/active_resource/collection.rb:67:in `collect!'
	from /home/pio/.rvm/gems/ruby-2.0.0-p247@werweisswas/gems/activeresource-4.0.0/lib/active_resource/base.rb:998:in `instantiate_collection'
	from /home/pio/.rvm/gems/ruby-2.0.0-p247@werweisswas/gems/activeresource-4.0.0/lib/active_resource/base.rb:959:in `find_every'
	from /home/pio/.rvm/gems/ruby-2.0.0-p247@werweisswas/gems/activeresource-4.0.0/lib/active_resource/base.rb:873:in `find'
	from /home/pio/.rvm/gems/ruby-2.0.0-p247@werweisswas/gems/activeresource-4.0.0/lib/active_resource/base.rb:899:in `all'
	from (irb):28
	from /home/pio/.rvm/gems/ruby-2.0.0-p247@werweisswas/gems/railties-4.0.0/lib/rails/commands/console.rb:90:in `start'
	from /home/pio/.rvm/gems/ruby-2.0.0-p247@werweisswas/gems/railties-4.0.0/lib/rails/commands/console.rb:9:in `start'
	from /home/pio/.rvm/gems/ruby-2.0.0-p247@werweisswas/gems/railties-4.0.0/lib/rails/commands.rb:64:in `<top (required)>'
	from script/rails:25:in `require'

**Comment by Coolnesss** [comment]
It seems this is still not fixed. Maybe it should be marked as a serious bug? It breaks my application's functionality completely, and the workaround in the comments doesn't seem to do anything.
