### ISSUE TITLE
Prevent mapping of nested attributes to Models

### ISSUE THREAD

**Issue by bwiggs** [rails/activeresource#91]
Is there any way to prevent ActiveResource from mapping nested attributes in an API response to Models within my application?

ex:

**API Response**

``` json
{

    "eventDate": "2012-09-29T23:00:00.000Z",
    "eventState": "final",
    "sport": {
        "sportName": "Football",
        "sportCode": "m-footbl"
    },
    "type": "SportsEvent",
    "uid": "stats-event-1180289",
}
```

I have a model called Sport, which seems to be getting mapped to that particular property. I'd like to prevent that from happening, possible?

**Comment by ArtieReus** [comment]
I found out another way to prevent this recursive creation of model objects in attributes hashes. You could add a class as following for each attribute you want to prevent nested object creation in your model class. 

Lets say you want that the attribute tags, which is a hash, to be ignored in your model. Add a class with the attribute name and override the initializer. It will assign directly the content to the attributes variable.

class OriginalModel < ActiveResource::Base

    class Tags < ActiveResource::Base
      def initialize(attributes = {}, persisted = false)
        @attributes     = attributes.with_indifferent_access
        @prefix_options = {}
        @persisted = persisted
      end
    end

end
