### ISSUE TITLE
Adding support for Authorization Token

### ISSUE THREAD

**Issue by pparidans** [rails/activeresource#98]
Allow to use Rest API secured using the ``Authorization: Token token=""`` HTTP header provided for example by the Rails' ``authenticate_or_request_with_http_token`` method.

**Comment by berkes** [comment]
Can this be closed? `self.headers['Authorization'] = 'Token token="abcd"'` solves the issue indeed.

**Comment by pparidans** [comment]
Documenting it and then close?
